### ISSUE TITLE
ERROR! no action detected in task. This often indicates a misspelled module name, or incorrect module path.

### ISSUE THREAD

**Issue by L3m0nb4tt3ry** [teacheraio/DevSecOps-Studio#10]
I have installed vagrant, virtualbox and  ansible from shared links.

When I try to execute "vagrant up", it gives below error. I got different kind of errors for rest of the machines as well. I tried to execute "vagrant provision DevSecOps-Box" but still facing same issue.
ERROR! no action detected in task. This often indicates a misspelled module name, or incorrect module path.

The error appears to have been in '/home/onkar/DevSecOps-Studio/provisioning/roles/devsecops/tasks/main.yml': line 30, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

- name: Clone git repos of needed code
  ^ here
![screenshot from 2018-04-18 14-56-57](https://user-images.githubusercontent.com/25724467/38923666-c6f8c9f4-4318-11e8-90f9-4013fa0fa073.png)

**Comment by secfigo** [comment]
Thanks for your report Onkar, I think I know whats the issue. Will fix it
today.

Meanwhile you can give the appliance a try, it should be available under
windows section, even though you are not using Windows OS, it's just
virtual box appliance.

**Comment by secfigo** [comment]
@L3m0nb4tt3ry I tried to reproduce the above error but couldn't.  Try updating the dependencies to the latest and try again ? 

Also please let me know the versions for virtualbox, vagrant and ansible so i can fix this for you.
`vboxmanage --version`
`vagrant version`
`ansible --version`
`python --version`

**Comment by L3m0nb4tt3ry** [comment]
Thank you for the response. I will try with appliance.
Below is the output.
![screenshot from 2018-04-19 10-19-08](https://user-images.githubusercontent.com/25724467/38971960-8587b702-43bb-11e8-948e-f5fb0d2f1b51.png)

**Comment by L3m0nb4tt3ry** [comment]
@secfigo I have tried with Windows set up option(Virtual Box). I have downloaded DevSecOps-v2.ova file and started all 4 machines. I got login screen on all of the 4 boxes. What are the login credentials ? I am not sure about the whole process. Am I missing something ?

**Comment by secfigo** [comment]
@L3m0nb4tt3ry password for everything is vagrant/vagrant

**Comment by L3m0nb4tt3ry** [comment]
@secfigo Got it working using Appliances. The Issue was whenever I tried to bring gitlab box up, it automatically set interface ip to 192.168.56.1 and  when I tried to access 10.0.1.15 it did not respond. So i changed that ip using 
`sudo ifconfig vboxnet0 10.0.1.1 netmask 255.255.255.0 up`
 and then I was able to access it.

**Comment by secfigo** [comment]
Glad you got it working :)

There is a django.nv project in it. Next steps is to integrate security
tooling it. Please use images available on my Docker hub to integrate tools

https://hub.docker.com/r/secfigo/

**Comment by L3m0nb4tt3ry** [comment]
@secfigo  Thanks,
I tried to add bandit.
1. Created a new file bandit.sh and paste your shell script from https://hub.docker.com/r/secfigo/
2. Modified .gitlab-ci.yml as below
```
test:
  stage: test
  script:
    - sudo chmod +x bandit.sh
    - ./bandit.sh
```
3. Encountered below error while running pipeline
(I executed same file on my local machine and it did run without any error.)

```
Running with gitlab-runner 10.5.0 (80b03db9)
  on gitlab-runner 9c26e0ad
Using Shell executor...
Running on gitlab-runner...
Fetching changes...
HEAD is now at b2d64c8 Update .gitlab-ci.yml
Checking out b2d64c81 as master...
Skipping Git submodules setup
$ sudo chmod +x bandit.sh
$ ./bandit.sh
Initially creating persistent directories
latest: Pulling from secfigo/bandit
ff3a5c916c92: Pulling fs layer
dd7b62403fcc: Pulling fs layer
5a9f804f5068: Pulling fs layer
5a9f804f5068: Verifying Checksum
5a9f804f5068: Download complete
ff3a5c916c92: Retrying in 5 seconds
ff3a5c916c92: Retrying in 4 seconds
ff3a5c916c92: Retrying in 3 seconds
ff3a5c916c92: Retrying in 2 seconds
ff3a5c916c92: Retrying in 1 second
....
ff3a5c916c92: Retrying in 4 seconds
ff3a5c916c92: Retrying in 3 seconds
ff3a5c916c92: Retrying in 2 seconds
ff3a5c916c92: Retrying in 1 second
ff3a5c916c92: Verifying Checksum
ff3a5c916c92: Download complete
ff3a5c916c92: Pull complete
dd7b62403fcc: Retrying in 5 seconds
dd7b62403fcc: Retrying in 4 seconds
dd7b62403fcc: Retrying in 3 seconds
dd7b62403fcc: Retrying in 2 seconds
dd7b62403fcc: Retrying in 1 second
.....
dd7b62403fcc: Retrying in 4 seconds
dd7b62403fcc: Retrying in 3 seconds
dd7b62403fcc: Retrying in 2 seconds
dd7b62403fcc: Retrying in 1 second
unexpected EOF
Unable to find image 'secfigo/bandit:latest' locally
latest: Pulling from secfigo/bandit
ff3a5c916c92: Pulling fs layer
dd7b62403fcc: Pulling fs layer
5a9f804f5068: Pulling fs layer
5a9f804f5068: Verifying Checksum
5a9f804f5068: Download complete
ff3a5c916c92: Retrying in 5 seconds
ff3a5c916c92: Retrying in 4 seconds
....
dd7b62403fcc: Retrying in 3 seconds
ff3a5c916c92: Retrying in 1 second
dd7b62403fcc: Retrying in 2 seconds
dd7b62403fcc: Retrying in 1 second
ff3a5c916c92: Verifying Checksum
ff3a5c916c92: Download complete
ff3a5c916c92: Pull complete
....
dd7b62403fcc: Retrying in 4 seconds
dd7b62403fcc: Retrying in 3 seconds
dd7b62403fcc: Retrying in 2 seconds
dd7b62403fcc: Retrying in 1 second
docker: unexpected EOF.
See 'docker run --help'.
ERROR: Job failed: exit status 1
```

**Comment by secfigo** [comment]
As discussed over the call, will send you more instructions for DevSecOps Integra Project.

**Comment by secfigo** [comment]
Closing this as we discussed this over the call.
