### ISSUE TITLE
Error with Ansible provisioning of DevSecOps-Box

### ISSUE THREAD

**Issue by chubirka** [teacheraio/DevSecOps-Studio#12]
Vagrant Up command fails on DevSecOps-Box provisioning:
TASK [rvm_io.ruby : Detect rvm binary] *****************************************
fatal: [DevSecOps-Box]: UNREACHABLE! => {"changed": false, "msg": "Authentication or permission failure. In some cases, you may have been able to authenticate and did not have permissions on the target directory. Consider changing the remote tmp path in ansible.cfg to a path rooted in \"/tmp\". Failed command was: ( umask 77 && mkdir -p \"` echo /home/vagrant/.ansible/tmp/ansible-tmp-1526613501.49-225377782606909 `\" && echo ansible-tmp-1526613501.49-225377782606909=\"` echo /home/vagrant/.ansible/tmp/ansible-tmp-1526613501.49-225377782606909 `\" ), exited with result 1", "unreachable": true}
	to retry, use: --limit @/Users/chubirka/DevSecOps-Studio/provisioning/devsecops-box.retry

PLAY RECAP *********************************************************************
DevSecOps-Box              : ok=22   changed=15   unreachable=1    failed=0   

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.

**Comment by secfigo** [comment]
Thanks @chubirka, its resolved now. Please let me know if you still face any issues.

**Comment by secfigo** [comment]
Closing this issue as all tests are green now and tested it locally.
