### ISSUE TITLE
gitlab_runner_coordinator_cert_path' is undefined

### ISSUE THREAD

**Issue by chubirka** [teacheraio/DevSecOps-Studio#29]
I received the following error when running "vagrant up." Was not able to determine root cause. 

TASK [jenkins : Copy gitlab server's public key to jenkins] ********************
fatal: [jenkins]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'gitlab_runner_coordinator_cert_path' is undefined\n\nThe error appears to have been in '/Users/USER_NAME/DevSecOps-Studio/provisioning/roles/jenkins/tasks/custom-certs.yml': line 9, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Copy gitlab server's public key to jenkins\n  ^ here\n"}

**Comment by secfigo** [comment]
PR is ready to be merged :)

**Comment by secfigo** [comment]
Fixed @chubirka, please let me know if you see any issues.
