### ISSUE TITLE
Setting Up Vagrant Boxes in parellel

### ISSUE THREAD

**Issue by raghunath24** [teacheraio/DevSecOps-Studio#39]
- Improving the setup time

**Comment by secfigo** [comment]
No support for this in vagrant. Close this for now.

![image](https://user-images.githubusercontent.com/11695998/41509715-a995c42e-728a-11e8-9b66-79eaf975def7.png)

**Comment by secfigo** [comment]
https://www.vagrantup.com/docs/virtualbox/usage.html
