### ISSUE TITLE
Add list of versions used for a successful provision of DevSecOps-Studio

### ISSUE THREAD

**Issue by seccodingguy** [teacheraio/DevSecOps-Studio#43]
Hello. I have been trying, unsuccessfully, for 4 days to get a successful install of the Studio using the Vagrant option. I have used multiple versions of Vagrant, Ansible, and VirtualBox - from the latest for all three to one or two versions back for all three. The newest version (5.2 for VB, 2.6 for Ansible, 2.1.2 for Vagrant) results in a SSH timeout issue, while the earlier versions either have issues with the syntax in the YAML files or a thread error is thrown with Ruby. The documentation for DevSecOps-Studio on teachera.io does not state provide guidance on what versions of the OS and required tools were used to successfully run vagrant.

Therefore, if you can provide me with the various versions you used to successfully execute vagrant and get all of the VM's up, provisioned, and communicating I will then duplicate my environment to try and execute and provision the Studio successfully.

**Comment by secfigo** [comment]
Sorry to hear that @seccodingguy, I will let you know the versions in an hour or so. I'm trying to replicate your error but having difficulty doing so. What OS are you using  ?

**Comment by secfigo** [comment]
I just tested the setup now, it works fine. Here are the versions I'm using currently 

$ vagrant --version
Vagrant 2.1.2

$ ansible --version
ansible 2.6.1
  config file = None
  configured module search path = [u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.14 

$ VirtualBox --help
Oracle VM VirtualBox Manager 5.2.8


Can you please provide your OS, vagrant, virtualbox and ansible versions ?

**Comment by secfigo** [comment]
Tested this on ubuntu 16.04 LTS as well 

$ vagrant --version
Vagrant 2.1.2

$ ansible --version
ansible 2.6.1
python version = 2.7.12

$ VirtualBox --help
Oracle VM VirtualBox Manager 5.2.16

**Comment by seccodingguy** [comment]
Thank you. I am going to try the install process on a new Macbook. Will post results.

**Comment by secfigo** [comment]
> Thank you. I am going to try the install process on a new Macbook. Will post results. I tried it on Ubuntu 18, 16.04, and MacOS High Sierra. The issue did come down to not having the latest version of Anisble. Also, Ansible does not install all of the necessary components when using PIP. When I installed Ansible stand-alone either by downloading directly or updating the repository in Ubuntu Vagrant executed without issue.

Thank you ! I have added explicitly more of the tooling via pip so they won't be missed.

> The other issue I did hit was the one I previously submitted related to Docker and the Anisble file. After adding a comment tag to the lines in the Ansible file the Vagrant process completed. However, I believe this is now having a secondary issue of Docker not being able to deploy a container in NGINX within the DevSecOps-Studio ecosystem.

Nginx is now added natively to the system so won't be an issue but will add more checks to ensure this doesn't happen in future.

> One final issue is quite a few tools appear to be missing from the VMs, i.e. scanning products. I can either create another issue or keep it here. Let me know.

Yeah, they are missing because we are pulling them from docker hub, please look at the wiki, you will understand. 

https://github.com/teacheraio/DevSecOps-Studio/wiki/Lesson-three:-Adding-SAST-and-DAST-into-the-pipeline 

I will close this issue soon as I have added bunch of tests and also list of version used in travis tests at https://travis-ci.org/teacheraio/DevSecOps-Studio/jobs/460084536

```bash
$ ansible --version
ansible 2.7.2
  config file = None
  configured module search path = [u'/home/travis/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/ansible
  executable location = /home/travis/virtualenv/python2.7.14/bin/ansible
  python version = 2.7.14 (default, Nov 28 2017, 18:46:37) [GCC 4.8.4]

$ molecule --version
molecule, version 2.19.0


$ docker --version
Docker version 18.06.1-ce, build e68fc7a


$ python --version
Python 2.7.14

$ pip --version
pip 9.0.1 from /home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages (python 2.7) 
```

**Comment by secfigo** [comment]
Please feel free to open this issue if error persists
