### ISSUE TITLE
Various errors with conditionals

### ISSUE THREAD

**Issue by seccodingguy** [teacheraio/DevSecOps-Studio#46]
Ran into several conditional errors in the YAML files. Quick work around is to simply comment the offending lines. Below is an example of just one error experienced:

fatal: [gitlab-runner]: FAILED! => {"msg": "The conditional check 'configured_runners.stderr.find(\"=shell\") != -1' failed. The error was: error while evaluating conditional (configured_runners.stderr.find(\"=shell\") != -1): 'dict object' has no attribute 'stderr'\n\nThe error appears to have been in '/home/mwireman/DevSecOps-Studio/provisioning/roles/gitlab-runner/tasks/register-runner.yml': line 9, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Uninstall existing gitlab-runner shell runner\n  ^ here\n"}

**Comment by davidcervigni-photobox** [comment]
I had a similar error, I had to comment out some "when" conditions: when: docker_package_state == present 


diff --git a/provisioning/roles/gitlab-runner/tasks/main.yml b/provisioning/roles/gitlab-runner/tasks/main.yml
index 0a7b3d5..b972074 100644
--- a/provisioning/roles/gitlab-runner/tasks/main.yml
+++ b/provisioning/roles/gitlab-runner/tasks/main.yml
@@ -87,4 +87,4 @@

 - name: Setup docker with self signed ssl
   include_tasks: docker.yml
-  when: docker_package_state == present
+  #when: docker_package_state == present
diff --git a/provisioning/roles/jenkins/tasks/main.yml b/provisioning/roles/jenkins/tasks/main.yml
index e9d5214..b694307 100644
--- a/provisioning/roles/jenkins/tasks/main.yml
+++ b/provisioning/roles/jenkins/tasks/main.yml
@@ -2,7 +2,7 @@

 - name: Setup docker with self signed ssl
   include_tasks: docker.yml
-  when: docker_package_state == present
+  #  when: docker_package_state == present

 - name: Add gitlab self signed ssl to trust store
   include_tasks: custom-certs.yml
diff --git a/provisioning/roles/prod/tasks/main.yml b/provisioning/roles/prod/tasks/main.yml
index 0346729..8e7dba4 100644
--- a/provisioning/roles/prod/tasks/main.yml
+++ b/provisioning/roles/prod/tasks/main.yml
@@ -5,5 +5,5 @@

 - name: Setup docker with self signed ssl
   include_tasks: docker.yml
-  when: docker_package_state == present
+  #  when: docker_package_state == present

**Comment by secfigo** [comment]
Looks like Ansible latest version want us to explicitly make variables are strings 

so instead of commenting it out, making docker_package_state == "present" in provisioning/gitlab-runner.yml  and in tasks of prod, jenkins and gitlab-runner fixes the issue.
