### ISSUE TITLE
Vagrant::Errors::VMBootTimeout

### ISSUE THREAD

**Issue by security-prince** [teacheraio/DevSecOps-Studio#48]
Hi Team,
I have been trying to setup DevSecOps-Studio for the past few hours, all goes well except for the vagrant up, it fails with the following error as shown in the screenshots.
Below are my OS and dependency details, do let me know if you need any more details for rectifying this issue.
```
root@ubuntu:/home/ishaq/Documents/DevSecOps-Studio# uname -a
Linux ubuntu 4.15.0-20-generic #21-Ubuntu SMP Tue Apr 24 06:16:15 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
root@ubuntu:/home/ishaq/Documents/DevSecOps-Studio# python --version
Python 2.7.15rc1
root@ubuntu:/home/ishaq/Documents/DevSecOps-Studio# pip --version
pip 9.0.1 from /usr/lib/python2.7/dist-packages (python 2.7)
root@ubuntu:/home/ishaq/Documents/DevSecOps-Studio# ansible --version
ansible 2.6.1
  config file = None
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.15rc1 (default, Apr 15 2018, 21:51:34) [GCC 7.3.0]
root@ubuntu:/home/ishaq/Documents/DevSecOps-Studio# vagrant --version
Vagrant 2.0.2
root@ubuntu:/home/ishaq/Documents/DevSecOps-Studio# 
```
![1](https://user-images.githubusercontent.com/5870952/42908939-f3fc2dc2-8aff-11e8-9427-2c3f9a36e2db.png)
![2](https://user-images.githubusercontent.com/5870952/42908940-f429edfc-8aff-11e8-9c02-bd4d26d4a81e.png)
![3](https://user-images.githubusercontent.com/5870952/42908941-f45753c8-8aff-11e8-8d5f-7869c2024e6f.png)

**Comment by kunwar-atul-hax0r** [comment]
Hi Team,

While doing vagrant up, it is throwing error, please refer the attached screenshots.

![image](https://user-images.githubusercontent.com/30471728/43121450-739336a4-8f3b-11e8-9b74-bbc72d614805.png)


![image](https://user-images.githubusercontent.com/30471728/43121472-7cf26c2e-8f3b-11e8-9919-b51c446ddb17.png)

**Comment by Chan9390** [comment]
Hey @security-prince Its just a timed out error. Try starting it again. If not then you have to alter some code to increase the timeout period.

**Comment by secfigo** [comment]
Hi @security-prince what version of vagrant and virtualbox do you have installed on your machine  ?

**Comment by security-prince** [comment]
Hi @secfigo , 
I am running Vagrant 2.0.2 and VirtualBox Graphical User Interface Version 5.2.10_Ubuntu r121806

**Comment by secfigo** [comment]
Please use latest vagrant version 2.1.2 and try again.

**Comment by security-prince** [comment]
Okay will try that, thanks
But just FYI I installed vagrant using apt-get and I got 2.0.2

**Comment by security-prince** [comment]
Hi @secfigo , i tried with vagrant 2.1.2 and still am facing the same issue are the versions of other required packages which I am using:

- ansible 2.6.1
- Python 2.7.15rc1
- Vagrant 2.1.2
- VirtualBox Graphical User Interface Version 5.2.16 r123759 (Qt5.9.5)

Please let me know if you need any further information.
![devsecopsstudio](https://user-images.githubusercontent.com/5870952/43190888-af86ab3c-9017-11e8-9da3-5718d3a668c2.png)

**Comment by Chan9390** [comment]
Hey @security-prince , its a time out error. Did you face any other errors before seeing this message in red color ?

**Comment by Chan9390** [comment]
It is common to see this issue with `bento` based Vagrant images. If it was the only error, then add the line `config.vm.boot_timeout = 600` (after line no [18](https://github.com/teacheraio/DevSecOps-Studio/blob/master/Vagrantfile#L18) ) to the Vagrantfile. 600 denotes the seconds to wait for connecting to ssh. You can add more than 600 also. Please reply if you face the issue again.

**Comment by security-prince** [comment]
Hi @Chan9390 , thanks for the response, prior to raising the issue I tried setting the timeout to 1000  which also didn't help. @secfigo has suggested somethings to try will try them and update here

**Comment by security-prince** [comment]
Hi @secfigo , i tried reinstalling, but still getting the same error, i also tried by adding config.vm.boot_timeout = 1000 to the vagrant file as suggested by @Chan9390

**Comment by secfigo** [comment]
I did some tests yesterday night. This is not an issue with DevSecOps
Studio, issue might be that you are installing virtualbox from deb repo.

please purge all packages of virtualbox and virtualbox-* and download it
directly from virtualbix.org instead

**Comment by kunwar-atul-hax0r** [comment]
Hi @secfigo ,

I'm also facing the same issue now as @security-prince is facing.

I have changed the Ubuntu 18.04 to 16.04, and also i have downloaded the virtual-box from the https://www.virtualbox.org/ after purging all the previous version of vm. Along with these things, i added config.vm.boot_timeout and also tried to change the box name to ubuntu/trusty64. 

Please refer the below screenshot for reference.

![screenshot_1](https://user-images.githubusercontent.com/30471728/43315566-f87b111e-91b3-11e8-81b3-acd09baa1e45.png)

**Comment by d78ui98** [comment]
Hello @security-prince  @kunwar-atul-hax0r 
> But just FYI I installed vagrant using apt-get and I got 2.0.2

It is not recommended to install vagrant with `apt` - https://www.vagrantup.com/intro/getting-started/install.html#caveats

 Purge old vagrant by following instructions here - https://github.com/openebs/openebs/issues/32#issue-210015847
Install new vagrant by following these instruction - https://github.com/docker-scripts/dev--LTSP#prerequisite

I justed tested out `DevSecOps-Studio` by following these instruction. It works perfectly.
Let me know if you face any issues :)

**Comment by secfigo** [comment]
Thanks @d78ui98 I didn't know that. I use MacOS to never came across this issue :)

**Comment by d78ui98** [comment]
No worries :)

**Comment by kunwar-atul-hax0r** [comment]
@d78ui98 thanks buddy, will see this.

**Comment by kunwar-atul-hax0r** [comment]
@secfigo i'm using DevSecOps studio inside a vm, so i think virtualbox does not like to run within virtualbox. Please refer the attached screenshot.

![image](https://user-images.githubusercontent.com/30471728/44321060-723b3300-a463-11e8-8568-1372354220ea.png)

**Comment by secfigo** [comment]
Yeah, thats true. If you want you can run Ansible scripts from another
linux machine.

**Comment by Chan9390** [comment]
@kunwar-atul-hax0r Fun fact: you can run VirtualBox inside of VMware VM.

**Comment by kunwar-atul-hax0r** [comment]
@Chan9390 i'm agree on this point 😅. But this comment was from vagrant creator not mine 🤐 🤐

**Comment by security-prince** [comment]
Thanks @d78ui98 , will try that, right now i am stuck with other stuffs, once i am done with those will try and let you know.
