### ISSUE TITLE
Vagrant up error in VM (Ubuntu 18.04 LTS (Bionic Beaver))

### ISSUE THREAD

**Issue by kunwar-atul-hax0r** [teacheraio/DevSecOps-Studio#49]
Hi Team,

I'm trying to setup DevSecOps studio in my Ubuntu 18.04 VM, all thing goes well except vagrant up.

Please refer the below details and attached error with my system details.

kunwar@kunwar:~/DevSecOps-Studio$ vagrant up

Bringing machine 'DevSecOps-Box' up with 'libvirt' provider...
Bringing machine 'jenkins' up with 'libvirt' provider...
Bringing machine 'gitlab' up with 'libvirt' provider...
Bringing machine 'gitlab-runner' up with 'libvirt' provider...
Bringing machine 'elk' up with 'libvirt' provider...
Bringing machine 'prod' up with 'libvirt' provider...
==> prod: An error occurred. The error will be shown after all tasks complete.
==> gitlab-runner: An error occurred. The error will be shown after all tasks complete.
==> gitlab: An error occurred. The error will be shown after all tasks complete.
==> DevSecOps-Box: An error occurred. The error will be shown after all tasks complete.
==> elk: An error occurred. The error will be shown after all tasks complete.
==> jenkins: An error occurred. The error will be shown after all tasks complete.
An error occurred while executing multiple actions in parallel.
Any errors that occurred are shown below.

An error occurred while executing the action on the 'DevSecOps-Box'
machine. Please handle this error then try again:

Error while connecting to libvirt: Error making a connection to libvirt URI qemu:///system?no_verify=1&keyfile=/home/kunwar/.ssh/id_rsa:
Call to virConnectOpen failed: Failed to connect socket to '/var/run/libvirt/libvirt-sock': No such file or directory

An error occurred while executing the action on the 'jenkins'
machine. Please handle this error then try again:

Error while connecting to libvirt: Error making a connection to libvirt URI qemu:///system?no_verify=1&keyfile=/home/kunwar/.ssh/id_rsa:
Call to virConnectOpen failed: Failed to connect socket to '/var/run/libvirt/libvirt-sock': No such file or directory

An error occurred while executing the action on the 'gitlab'
machine. Please handle this error then try again:

Error while connecting to libvirt: Error making a connection to libvirt URI qemu:///system?no_verify=1&keyfile=/home/kunwar/.ssh/id_rsa:
Call to virConnectOpen failed: Failed to connect socket to '/var/run/libvirt/libvirt-sock': No such file or directory

An error occurred while executing the action on the 'gitlab-runner'
machine. Please handle this error then try again:

Error while connecting to libvirt: Error making a connection to libvirt URI qemu:///system?no_verify=1&keyfile=/home/kunwar/.ssh/id_rsa:
Call to virConnectOpen failed: Failed to connect socket to '/var/run/libvirt/libvirt-sock': No such file or directory

An error occurred while executing the action on the 'elk'
machine. Please handle this error then try again:

Error while connecting to libvirt: Error making a connection to libvirt URI qemu:///system?no_verify=1&keyfile=/home/kunwar/.ssh/id_rsa:
Call to virConnectOpen failed: Failed to connect socket to '/var/run/libvirt/libvirt-sock': No such file or directory

An error occurred while executing the action on the 'prod'
machine. Please handle this error then try again:

Error while connecting to libvirt: Error making a connection to libvirt URI qemu:///system?no_verify=1&keyfile=/home/kunwar/.ssh/id_rsa:
Call to virConnectOpen failed: Failed to connect socket to '/var/run/libvirt/libvirt-sock': No such file or directory

![details](https://user-images.githubusercontent.com/30471728/43122432-a4cc357e-8f3e-11e8-8433-308cb2ba0e46.png)

![vag](https://user-images.githubusercontent.com/30471728/43122439-aae3b086-8f3e-11e8-8bef-b46549299fdb.png)

![vagr](https://user-images.githubusercontent.com/30471728/43122450-b13530a4-8f3e-11e8-9b30-0201f05d9ed2.png)

**Comment by d78ui98** [comment]
I would suggest purge the old vagrant package and Install it again by this -
```
wget https://releases.hashicorp.com/vagrant/2.1.2/vagrant_2.1.2_x86_64.deb
sudo dpkg -i vagrant_2.1.2_x86_64.deb
vagrant -v
```

Then try bringing up the machine individually. Because the message says -
```
An error occurred while executing multiple actions in parallel.
Any errors that occurred are shown below.
```

**Comment by secfigo** [comment]
@kunwar-atul-hax0r Please install virtualbox, vagrant and try again. We currently support only virtualbox as hypervisor.

I'm closing this issue but feel free to re-open if that doesn't resolve your issue.

**Comment by heshand** [comment]
same issue for me as well

**Comment by PjDev09** [comment]
Same issue for me too
