### ISSUE TITLE
ERROR ZAP failed to access: http://10.0.1.22

### ISSUE THREAD

**Issue by derweiser** [teacheraio/DevSecOps-Studio#52]
Environment: Windows DevSecOps Studio image. 
Issue: the pipeline has the following command in the .gitlab-ci.yml file "**docker run -t owasp/zap2docker-stable zap-baseline.py -d -t http://10.0.1.22/**"

This causes the following error:

ERROR ZAP failed to access: http://10.0.1.22

Fix - as per Lesson Three, need to add port 8000 at the end "**docker run -t owasp/zap2docker-stable zap-baseline.py -t http://10.0.1.22:8000/**"

This now works

**Comment by secfigo** [comment]
Thanks @derweiser fixed :)
