### ISSUE TITLE
Failed to validate the SSL certificate for github.com:443

### ISSUE THREAD

**Issue by seccodingguy** [teacheraio/DevSecOps-Studio#53]
Environment
Vagrant 2.1.2
VirtualBox 5.2.16r123759
ansible 2.6.2
  config file = None
  configured module search path = [u'/Users/mwireman/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Library/Python/2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.10 (default, Oct  6 2017, 22:29:07) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)]

OS
macOS (10.13.6)

Full console output

The exact steps (shown via the output) for the issue when installing Docker is here:

TASK [geerlingguy.docker : Add Docker repository.] *****************************
changed: [DevSecOps-Box]

TASK [geerlingguy.docker : Install Docker.] ************************************
changed: [DevSecOps-Box]

TASK [geerlingguy.docker : Ensure Docker is started and enabled at boot.] ******
ok: [DevSecOps-Box]

RUNNING HANDLER [geerlingguy.docker : restart docker] **************************
changed: [DevSecOps-Box]

TASK [geerlingguy.docker : include_tasks] **************************************
included: /Users/mwireman/DevSecOps-Studio/provisioning/roles/geerlingguy.docker/tasks/docker-compose.yml for DevSecOps-Box

TASK [geerlingguy.docker : Check current docker-compose version.] **************
ok: [DevSecOps-Box]

TASK [geerlingguy.docker : Delete existing docker-compose version if it's different.] ***
skipping: [DevSecOps-Box]

TASK [geerlingguy.docker : Install Docker Compose (if configured).] ************
fatal: [DevSecOps-Box]: FAILED! => {"changed": false, "msg": "Failed to validate the SSL certificate for github.com:443. Make sure your managed systems have a valid CA certificate installed. You can use validate_certs=False if you do not need to confirm the servers identity but this is unsafe and not recommended. Paths checked for this platform: /etc/ssl/certs, /etc/pki/ca-trust/extracted/pem, /etc/pki/tls/certs, /usr/share/ca-certificates/cacert.org, /etc/ansible. The exception msg was: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)."}
to retry, use: --limit @/.../DevSecOps-Studio/provisioning/devsecops-box.retry

PLAY RECAP *********************************************************************
DevSecOps-Box : ok=14 changed=7 unreachable=0 failed=1

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.

**Comment by secfigo** [comment]
Hi @seccodingguy could you please try with the following versions, seems to working fine.

```
Vagrant 2.2.0
ansible 2.7.2 
```

**Comment by secfigo** [comment]
Looks like it was because of stale vagrant box, goes away if you do `vagrant box update`
