### ISSUE TITLE
Nested Virtualization

### ISSUE THREAD

**Issue by bibkam** [teacheraio/DevSecOps-Studio#56]
Hello,

I tried to deploy DevSecOps-Studio on my Virtualbox (5.2.x) but it seems not working for these reasons:
1- DevSecOps-Studio create/manage VMs with 64-bits architecture
2- VirtualBox allows nested virtualization,but, only for 32-bits architecture.

Could you confirm that nested virtualization doesn't work ? what do suggest to bypass this constraint ?
BR
K

**Comment by teacheraio** [comment]
@bibkam @security-prince nested virtualization is not recommended and not supported either. Please run it natively or use the already created VM images (see README.md)
