### ISSUE TITLE
getting problem with ansible on windows

### ISSUE THREAD

**Issue by eidelweiss** [teacheraio/DevSecOps-Studio#7]
always get error "**name to long**" with ansible thing.

when try to install the ansible with the following command
``pip install git+https://github.com/ansible/ansible.git@devel``

getting this error

![error](https://user-images.githubusercontent.com/18359562/37514389-651d1eb2-293a-11e8-9ea6-609767c27503.jpg)

here is the original file name, when i check the full path
![filename](https://user-images.githubusercontent.com/18359562/37514450-8be95fba-293a-11e8-9287-baac24f58f79.jpg)

**Comment by secfigo** [comment]
Thanks Randy for the issue report. I'm aware of this issue, will update
with instructions this monday.

Meanwhile try this, it should work -
https://www.jeffgeerling.com/blog/running-ansible-within-windows

If not, you can

1. Download DevSecOps-Studio Appliance (4.45 GB) from this link,
https://drive.google.com/open?id=1b3Z6BLndohpn_2HHcBfPFUpoSx78OKgG

2. Import the above Appliance by following these step
https://docs.oracle.com/cd/E26217_01/E26796/html/qs-import-vm.html

**Comment by secfigo** [comment]
We are moving to VirtualBox appliance going forward, so you won't see these issues.
