### ISSUE TITLE
Link to DevSecOps-Course does not work -> 404

### ISSUE THREAD

**Issue by WittmannJ** [teacheraio/DevSecOps-Studio#70]
location of the Problem: readme.md

This link: https://www.practical-devsecops.com/free-practical-devsecops-course/ which should lead to the DevSecOps-Course only retrieves a 404 not found. Please fix the link or reupload the course on practical-devsecops.com.

Thank you

WittmannJ

**Comment by ammarion** [comment]
I still can't access that link

**Comment by bhatisunil2706** [comment]
Is the free course available as it (https://www.practical-devsecops.com/free-practical-devsecops-course/) gives No Results Found

**Comment by teacheraio** [comment]
Please try here - https://www.practical-devsecops.com/free-devsecops-course/
