### ISSUE TITLE
rvm_io.ruby should be replaced by rvm.ruby

### ISSUE THREAD

**Issue by tiwatsuka** [teacheraio/DevSecOps-Studio#71]
Provisioning by ansible fails with gpg error while executing "TASK [rvm_io.ruby : Install rvm]".
It might be related to https://github.com/rvm/rvm/issues/3110 and https://github.com/rvm/rvm1-ansible/issues/186 .

Because this project include and use old rvm_io.ruby role, the problem occurs even though it's already resolved in latest version of rvm1-ansible.
It should be replaced by latest rvm.ruby role.

**Comment by secfigo** [comment]
Thanks for raising this issue here @tiwatsuka I will fix it today

**Comment by secfigo** [comment]
Fixed in #73
