### ISSUE TITLE
fatal: [gitlab-runner]: FAILED!

### ISSUE THREAD

**Issue by bhatisunil2706** [teacheraio/DevSecOps-Studio#72]
Getting error while doing vagrant provision gitlab-runner. Below is the error - 

TASK [rvm_io.ruby : Install rvm] ***********************************************
fatal: [gitlab-runner]: FAILED! => {"changed": true, "cmd": ["/tmp/rvm-installer.sh", "stable", "--path", "/usr/local/rvm", "--auto-dotfiles", "--user-install"], "delta": "0:00:10.576713", "end": "2018-12-23 16:39:34.317252", "msg": "non-zero return code", "rc": 2, "start": "2018-12-23 16:39:23.740539", "stderr": "gpg: Signature made Thu 13 Dec 2018 03:09:53 PM UTC using RSA key ID 39499BDB\ngpg: Can't check signature: public key not found", "stderr_lines": ["gpg: Signature made Thu 13 Dec 2018 03:09:53 PM UTC using RSA key ID 39499BDB", "gpg: Can't check signature: public key not found"], "stdout": "Turning on auto dotfiles mode.\nTurning on user install mode.\nDownloading https://github.com/rvm/rvm/archive/1.29.6.tar.gz\nDownloading https://github.com/rvm/rvm/releases/download/1.29.6/1.29.6.tar.gz.asc\nGPG signature verification failed for '/usr/local/rvm/archives/rvm-1.29.6.tgz' - 'https://github.com/rvm/rvm/releases/download/1.29.6/1.29.6.tar.gz.asc'! Try to install GPG v2 and then fetch the public key:\n\n    sudo gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB\n\nor if it fails:\n\n    command curl -sSL https://rvm.io/mpapis.asc | sudo gpg --import -\n    command curl -sSL https://rvm.io/pkuczynski.asc | sudo gpg --import -\n\nIn case of further problems with validation please refer to https://rvm.io/rvm/security", "stdout_lines": ["Turning on auto dotfiles mode.", "Turning on user install mode.", "Downloading https://github.com/rvm/rvm/archive/1.29.6.tar.gz", "Downloading https://github.com/rvm/rvm/releases/download/1.29.6/1.29.6.tar.gz.asc", "GPG signature verification failed for '/usr/local/rvm/archives/rvm-1.29.6.tgz' - 'https://github.com/rvm/rvm/releases/download/1.29.6/1.29.6.tar.gz.asc'! Try to install GPG v2 and then fetch the public key:", "", "    sudo gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB", "", "or if it fails:", "", "    command curl -sSL https://rvm.io/mpapis.asc | sudo gpg --import -", "    command curl -sSL https://rvm.io/pkuczynski.asc | sudo gpg --import -", "", "In case of further problems with validation please refer to https://rvm.io/rvm/security"]}
	to retry, use: --limit @/Users/user/Documents/tools/DevSecOps-Studio/provisioning/gitlab-runner.retry

PLAY RECAP *********************************************************************
gitlab-runner              : ok=10   changed=2    unreachable=0    failed=1   

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.

**Comment by secfigo** [comment]
Fixed in #73 please git pull and try again.
